### ISSUE TITLE
Can not create new system using main.go as template.

### ISSUE THREAD

**Issue by mmsh1** [cobbler/cobblerclient#3] opened 2021-02-16 15:58 UTC
Hello! I'm trying to use cobblerclient to interact with remote cobbler (it is in docker container). I'm using main.go as a template. Unfortunately, it fails on creating system stage and I don't know how to fix it. 
First, it failed to creating system due to lack of string "PowerType: "ipmitool"" in new System description. After adding this line system creation fails with python exception: 
```
Error creating system: Fault(1): <class 'AttributeError'>:'str' object has no attribute 'copy'.

2021-02-16T15:43:36 - INFO | Exception Info:
  File "/usr/lib/python3.9/site-packages/cobbler/remote.py", line 3473, in _dispatch
    return method_handle(*params)

  File "/usr/lib/python3.9/site-packages/cobbler/remote.py", line 1949, in save_system
    return self.save_item("system", object_id, token, editmode=editmode)

  File "/usr/lib/python3.9/site-packages/cobbler/remote.py", line 1912, in save_item
    self.api.add_item(what, obj, logger=self.logger)

  File "/usr/lib/python3.9/site-packages/cobbler/api.py", line 739, in add_item
    self.get_items(what).add(ref, check_for_duplicate_names=check_for_duplicate_names, save=save, logger=logger)

  File "/usr/lib/python3.9/site-packages/cobbler/cobbler_collections/collection.py", line 398, in add
    self.lite_sync.add_single_system(ref.name)

  File "/usr/lib/python3.9/site-packages/cobbler/actions/litesync.py", line 207, in add_single_system
    self.tftpd.add_single_system(system)

  File "/usr/lib/python3.9/site-packages/cobbler/modules/managers/in_tftpd.py", line 148, in add_single_system
    self.tftpgen.write_templates(system)

  File "/usr/lib/python3.9/site-packages/cobbler/tftpgen.py", line 863, in write_templates
    blended = utils.blender(self.api, False, obj)

  File "/usr/lib/python3.9/site-packages/cobbler/utils.py", line 641, in blender
    __consolidate(node, results)

  File "/usr/lib/python3.9/site-packages/cobbler/utils.py", line 793, in __consolidate
    results[field].update(data_item.copy())
```

Here is my System object description

```
s := cobbler.System{
  Name: "Foobar",
  Profile: "Testy",
  BootLoader: "grub",
  NameServers: []string{"8.8.8.8", "1.1.1.1"},
  PowerID: "",
  PowerType: "ipmitool",
}

```
Any help would be appreciated.

**Comment by SchoolGuy** [comment] 2021-09-29 13:25
Sorry for taking so long. Don't know why my notifications didn't kick in there...

This should be resolved with a more recent version of Cobbler. If not then I'll need to investigate deeper!

**Comment by holmesb** [comment] 2022-01-26 13:56
This is fixed

**Comment by SchoolGuy** [comment] 2022-01-26 14:30
Okay since @holmesb confirmed, I will close the issue.

**Closed as completed by SchoolGuy** 2022-01-26 14:30 UTC
